### ISSUE TITLE
Look into flaky test

### ISSUE THREAD

**Issue by hzxcaryn** [googleinterns/gpay-group-buy#136]
Integration test fails randomly. Here is an example of a failed test output 
```
Setting up Datastore Emulator...
[datastore] The health check endpoint for this emulator instance is http://localhost:8081/Jul 17, 2020 5:15:23 AM io.gapi.emulators.grpc.GrpcServer$3 operationComplete
[datastore] INFO: Adding handler(s) to newly registered Channel.
[datastore] Jul 17, 2020 5:15:23 AM io.gapi.emulators.netty.HttpVersionRoutingHandler channelRead
[datastore] INFO: Detected HTTP/2 connection.
[datastore] Jul 17, 2020 5:15:25 AM io.gapi.emulators.grpc.GrpcServer$3 operationComplete
[datastore] INFO: Adding handler(s) to newly registered Channel.
[datastore] Jul 17, 2020 5:15:25 AM io.gapi.emulators.netty.HttpVersionRoutingHandler channelRead
[datastore] INFO: Detected HTTP/2 connection.
FAIL tests/integration/commits.test.ts
  ● Commits endpoints › GET /commits › Should filter by listingId query param
    expect(received).toEqual(expected) // deep equality
    - Expected  - 7
    + Received  + 0
    @@ -4,13 +4,6 @@
          "createdAt": "2020-06-23T03:34:00.000Z",
          "customerId": 1,
          "id": 1,
          "listingId": 1,
        },
    -   Object {
    -     "commitStatus": "ongoing",
    -     "createdAt": "2020-06-29T03:34:00.000Z",
    -     "customerId": 2,
    -     "id": 2,
    -     "listingId": 1,
    -   },
      ]
      41 | 
      42 |       expect(res.status).toBe(200);
    > 43 |       expect(res.body).toEqual(expectedCommitData);
         |                        ^
      44 |     });
      45 | 
      46 |     test('Should filter by customerId query param', async () => {
      at tests/integration/commits.test.ts:43:24
      at fulfilled (tests/integration/commits.test.ts:20:58)
[datastore] Jul 17, 2020 5:15:26 AM io.gapi.emulators.grpc.GrpcServer$3 operationComplete
[datastore] INFO: Adding handler(s) to newly registered Channel.
[datastore] Jul 17, 2020 5:15:26 AM io.gapi.emulators.netty.HttpVersionRoutingHandler channelRead
[datastore] INFO: Detected HTTP/2 connection.
PASS tests/integration/customers.test.ts
Test Suites: 1 failed, 1 passed, 2 total
Tests:       1 failed, 6 passed, 7 total
Snapshots:   0 total
Time:        2.515 s
Ran all test suites.
Tearing down Datastore Emulator...
[datastore] Jul 17, 2020 5:15:26 AM io.gapi.emulators.grpc.GrpcServer$3 operationComplete
[datastore] INFO: Adding handler(s) to newly registered Channel.
[datastore] Jul 17, 2020 5:15:26 AM io.gapi.emulators.netty.HttpVersionRoutingHandler channelRead
[datastore] INFO: Detected non-HTTP/2 connection.
Force exiting Jest: Have you considered using `--detectOpenHandles` to detect async operations that kept running after all tests finished?
error Command failed with exit code 1.
```
Here is an example of a passing test output:
```
Setting up Datastore Emulator...
[datastore] The health check endpoint for this emulator instance is http://localhost:8081/Jul 17, 2020 5:22:14 AM io.gapi.emulators.grpc.GrpcServer$3 operationComplete
[datastore] INFO: Adding handler(s) to newly registered Channel.
[datastore] Jul 17, 2020 5:22:14 AM io.gapi.emulators.netty.HttpVersionRoutingHandler channelRead
[datastore] INFO: Detected HTTP/2 connection.
[datastore] Jul 17, 2020 5:22:16 AM io.gapi.emulators.grpc.GrpcServer$3 operationComplete
[datastore] INFO: Adding handler(s) to newly registered Channel.
[datastore] Jul 17, 2020 5:22:16 AM io.gapi.emulators.netty.HttpVersionRoutingHandler channelRead
[datastore] INFO: Detected HTTP/2 connection.
PASS tests/integration/commits.test.ts
[datastore] Jul 17, 2020 5:22:17 AM io.gapi.emulators.grpc.GrpcServer$3 operationComplete
[datastore] INFO: Adding handler(s) to newly registered Channel.
[datastore] Jul 17, 2020 5:22:17 AM io.gapi.emulators.netty.HttpVersionRoutingHandler channelRead
[datastore] INFO: Detected HTTP/2 connection.
PASS tests/integration/customers.test.ts
Test Suites: 2 passed, 2 total
Tests:       7 passed, 7 total
Snapshots:   0 total
Time:        2.666 s
Ran all test suites.
Tearing down Datastore Emulator...
[datastore] Jul 17, 2020 5:22:17 AM io.gapi.emulators.grpc.GrpcServer$3 operationComplete
[datastore] INFO: Adding handler(s) to newly registered Channel.
[datastore] Jul 17, 2020 5:22:17 AM io.gapi.emulators.netty.HttpVersionRoutingHandler channelRead
[datastore] INFO: Detected non-HTTP/2 connection.
Force exiting Jest: Have you considered using `--detectOpenHandles` to detect async operations that kept running after all tests finished?
```

**Comment by hzxcaryn** [comment]
Looks like this is not happening anymore, closing this!
